import type { ChangelogEntry } from './types';

// Dari yang terbaru. Setiap kali versi naik, tambahkan entri di paling atas (dan perbarui current-release.ts).
export const CHANGELOG_ENTRIES: readonly ChangelogEntry[] = [
  {
    kind: 'version',
    versionLabel: 'v0.12.0',
    latestVersion: '0.12.0',
    date: '2026-10-10',
    title: 'Apa yang baru & Segera hadir',
    items: [
      { text: 'Halaman baru **"Apa yang baru"** berisi daftar perubahan aplikasi di setiap versi.' },
      { text: 'Tab **"Segera hadir"** menunjukkan fitur yang sedang disiapkan dan yang masih dipertimbangkan.' },
      { text: 'Setelah aplikasi diperbarui, muncul pemberitahuan singkat dengan tombol untuk melihat perubahannya.' },
    ],
  },
  {
    kind: 'version',
    versionLabel: 'v0.11.2',
    latestVersion: '0.11.2',
    date: '2026-10-09',
    title: 'Lupa PIN & perbaikan kecil',
    items: [
      { ownerOnly: true, text: 'Lupa PIN? Sekarang PIN bisa diganti langsung dari Pengaturan memakai kode pemulihan, tanpa harus masuk Mode Kasir dulu.' },
      { ownerOnly: true, text: 'Nilai stok tidak lagi tampil negatif bila stok barang minus. Stok minus dihitung 0, sama seperti di laporan.' },
      { ownerOnly: true, text: 'Petunjuk di form barang kini menyebut batas menipis default sesuai yang Anda atur di Pengaturan.' },
      { ownerOnly: true, text: 'Kalau lonceng peringatan dimatikan, kasir tidak bisa membuka halaman Peringatan stok.' },
    ],
  },
  {
    kind: 'version',
    versionLabel: 'v0.11.1',
    latestVersion: '0.11.1',
    date: '2026-10-09',
    title: 'Panduan tanpa meninggalkan halaman',
    items: [
      { text: 'Panduan kini terbuka sebagai jendela di atas halaman yang sedang Anda pakai. Keranjang Kasir dan isian form tidak hilang.' },
      { text: 'Di HP, panduan muncul dari bawah layar dan bisa ditutup dengan menggesernya ke bawah atau menekan tombol kembali.' },
      { text: 'Tombol di bawah panduan menyebut tujuannya, misalnya "Buka Pengaturan".' },
    ],
  },
  {
    kind: 'version',
    versionLabel: 'v0.11.0',
    latestVersion: '0.11.0',
    date: '2026-10-09',
    title: 'Panduan di dalam aplikasi',
    items: [
      { text: 'Halaman **Bantuan** baru berisi 20 topik cara memakai aplikasi, dari menambah barang sampai membaca laporan.' },
      { text: 'Tombol **?** di samping judul halaman langsung membuka panduan untuk halaman itu.' },
      { text: 'Panduan bisa dicari lewat Cari (Ctrl K / ⌘K), misalnya dengan mengetik "retur" atau "HPP".' },
    ],
  },
  {
    kind: 'version',
    versionLabel: 'v0.10.5',
    latestVersion: '0.10.5',
    date: '2026-10-08',
    title: 'Layar offline yang lebih jelas',
    items: [
      { text: 'Kalau internet putus, layar memberi tahu halaman mana yang belum bisa dibuka, dan berganti sendiri begitu koneksi kembali.' },
    ],
  },
  {
    kind: 'version',
    versionLabel: 'v0.10.4',
    latestVersion: '0.10.4',
    date: '2026-10-08',
    title: 'Halaman error yang ramah',
    items: [
      { text: 'Alamat yang salah, gangguan penyimpanan, dan kesalahan tak terduga kini tampil sebagai layar yang menjelaskan masalahnya dalam bahasa sehari-hari, lengkap dengan tombol untuk melanjutkan.' },
      { text: 'Saat aplikasi baru diperbarui, Anda diberi tahu "Versi baru tersedia" dan cukup memuat ulang halaman.' },
    ],
  },
  {
    kind: 'version',
    versionLabel: 'v0.10.3',
    latestVersion: '0.10.3',
    date: '2026-10-07',
    title: 'Data contoh',
    items: [
      { ownerOnly: true, text: 'Tombol **"Muat data contoh"** mengisi aplikasi dengan 20 barang dan 60 hari transaksi, supaya semua fitur bisa dicoba sebelum Anda memasukkan data sendiri.' },
      { ownerOnly: true, text: 'Data contoh bisa dihapus lagi dengan satu tombol.' },
    ],
  },
  {
    kind: 'version',
    versionLabel: 'v0.10.2',
    latestVersion: '0.10.2',
    date: '2026-10-07',
    title: 'Tanda pengembang',
    items: [{ ownerOnly: true, text: 'Nama pengembang (dev.myrules) kini tampil di bawah nomor versi di Pengaturan.' }],
  },
  {
    kind: 'version',
    versionLabel: 'v0.10.1',
    latestVersion: '0.10.1',
    date: '2026-10-07',
    title: 'Perapian',
    items: [{ text: 'Perapian di balik layar supaya aplikasi lebih mudah dirawat. Tidak ada perubahan yang terlihat.' }],
  },
  {
    kind: 'version',
    versionLabel: 'v0.10.0',
    latestVersion: '0.10.0',
    date: '2026-10-07',
    title: 'Cari cepat & dasbor layar lebar',
    items: [
      { text: '**Cari (Ctrl K / ⌘K):** pindah halaman, cari barang, atau jalankan aksi cepat seperti "Barang masuk…" dari mana saja.' },
      { ownerOnly: true, text: 'Di layar komputer, Dasbor, Laporan, dan Analisis produk tersusun dalam kotak-kotak sehingga lebih banyak yang terlihat sekaligus.' },
    ],
  },
  {
    kind: 'phase',
    phaseLabel: 'Fase UI',
    versionLabel: 'v0.9.0 – v0.9.1',
    latestVersion: '0.9.1',
    date: '2026-10-06',
    title: 'Tampilan baru',
    items: [
      { text: 'Tampilan baru dengan warna krem dan oranye, huruf yang lebih mudah dibaca, serta tombol yang lebih besar dan nyaman disentuh.' },
      { text: 'Menu bawah ber-ikon di HP dan menu di atas di komputer. Nama toko tampil di bagian atas.' },
      { text: 'Kasir lebih cepat di HP: bar "Bayar" di bawah layar dan panel pembayaran yang muncul dari bawah.' },
      { text: 'Filter Stok dan Riwayat dipindah ke panel tersendiri, sehingga daftar langsung terlihat.' },
      { text: 'Gerak halus saat berpindah halaman dan saat daftar berubah urutan. Halaman Kasir tetap tanpa animasi supaya cepat.' },
    ],
  },
  {
    kind: 'phase',
    phaseLabel: 'Fase 4',
    versionLabel: 'v0.7.0 – v0.8.0',
    latestVersion: '0.8.0',
    date: '2026-10-05',
    title: 'Laporan',
    items: [
      { ownerOnly: true, text: 'Empat laporan: **Penjualan**, **Laba kotor**, **Stok** per tanggal, dan **Pergerakan stok**.' },
      { ownerOnly: true, text: 'Setiap laporan bisa dicetak atau disimpan sebagai PDF, dan diunduh sebagai CSV atau Excel.' },
      { ownerOnly: true, text: '**Profil toko** (nama, alamat, telepon, logo) tampil di kepala setiap laporan.' },
    ],
  },
  {
    kind: 'phase',
    phaseLabel: 'Fase 3',
    versionLabel: 'v0.6.1 – v0.6.3',
    latestVersion: '0.6.3',
    date: '2026-10-04',
    title: 'Dasbor & peringatan stok',
    items: [
      { ownerOnly: true, text: '**Dasbor:** omzet, jumlah transaksi, rata-rata transaksi, dan laba kotor, dibandingkan dengan periode sebelumnya, ditambah grafik tren, omzet per kategori, dan jam sibuk.' },
      { ownerOnly: true, text: '**Analisis produk:** barang terlaris, barang lambat laku, perkiraan kapan stok habis, dan barang penyumbang 80% omzet.' },
      { text: '**Peringatan stok:** lonceng memberi tahu barang yang menipis atau habis.' },
      { ownerOnly: true, text: 'Daftar belanja ke supplier bisa dibagikan lewat WhatsApp.' },
    ],
  },
  {
    kind: 'phase',
    phaseLabel: 'Fase 2',
    versionLabel: 'v0.6.0',
    latestVersion: '0.6.0',
    date: '2026-10-03',
    title: 'Kasir & penjualan',
    items: [
      { text: '**Kasir:** cari barang, atur jumlah, beri diskon, lalu bayar Tunai, Transfer, atau QRIS. Stok berkurang otomatis.' },
      { ownerOnly: true, text: '**Riwayat penjualan** lengkap dengan **retur** dan **pembatalan** transaksi.' },
      { text: '**Mode Kasir dengan PIN:** karyawan bisa berjualan tanpa melihat harga beli, laba, atau laporan.' },
      { ownerOnly: true, text: 'Kelola **kategori**, ubah harga (dengan riwayat harga), arsipkan barang, dan tambahkan foto barang.' },
      { ownerOnly: true, text: '**Impor barang** sekaligus dari file Excel atau CSV.' },
    ],
  },
  {
    kind: 'phase',
    phaseLabel: 'Fase 1',
    versionLabel: 'v0.1.0 – v0.5.0',
    latestVersion: '0.5.0',
    date: '2026-10-02',
    title: 'Stok barang',
    items: [
      { text: 'Daftar stok dengan pencarian, filter kategori dan status (Aman, Menipis, Habis), serta pengurutan.' },
      { ownerOnly: true, text: 'Tambah barang baru dan catat barang masuk atau koreksi hasil hitung stok.' },
      { text: 'Detail barang dengan riwayat pergerakan stok: kapan bertambah atau berkurang, dan sebabnya.' },
    ],
  },
];
