import type { HelpGroup, HelpTopicMeta } from './types';

export const HELP_GROUPS: readonly { id: HelpGroup; title: string }[] = [
  { id: 'memulai', title: 'Memulai' },
  { id: 'harian', title: 'Harian' },
  { id: 'hasil', title: 'Melihat hasil' },
  { id: 'mengatur', title: 'Mengatur' },
  { id: 'istilah', title: 'Istilah & masalah umum' },
];

export const HELP_TOPICS = [
  {
    slug: 'mulai',
    title: 'Mulai di sini',
    group: 'memulai',
    summary: 'Aplikasi ini mencatat stok barang dan penjualan toko Anda, lalu merangkumnya menjadi dasbor dan laporan.',
    keywords: 'awal pertama mulai langkah menu',
    audience: 'owner',
  },
  {
    slug: 'profil-toko',
    title: 'Profil toko',
    group: 'memulai',
    summary: 'Nama, alamat, telepon, dan logo toko dipakai di kepala (kop) laporan.',
    keywords: 'nama toko alamat logo kop telepon',
    audience: 'owner',
    openPage: '/pengaturan',
  },
  {
    slug: 'tambah-barang',
    title: 'Menambah barang',
    group: 'memulai',
    summary: 'Mendaftarkan barang yang dijual di toko, lengkap dengan harga dan stok awalnya.',
    keywords: 'barang baru sku produk daftar',
    audience: 'owner',
    openPage: '/stok/baru',
  },
  {
    slug: 'impor-barang',
    title: 'Impor barang dari Excel',
    group: 'memulai',
    summary: 'Memasukkan banyak barang sekaligus dari file Excel (.xlsx) atau CSV.',
    keywords: 'excel csv file banyak template',
    audience: 'owner',
    openPage: '/stok/impor',
  },
  {
    slug: 'data-contoh',
    title: 'Mencoba dengan data contoh',
    group: 'memulai',
    summary: 'Mengisi aplikasi dengan 20 barang dan 60 hari transaksi contoh, termasuk retur dan pembatalan.',
    keywords: 'contoh demo coba percobaan',
    audience: 'owner',
    openPage: '/pengaturan',
  },
  {
    slug: 'kasir',
    title: 'Mencatat penjualan di Kasir',
    group: 'harian',
    summary: 'Mencatat setiap penjualan.',
    keywords: 'jual bayar transaksi keranjang kembalian diskon',
    audience: 'all',
    openPage: '/kasir',
  },
  {
    slug: 'stok',
    title: 'Melihat daftar stok',
    group: 'harian',
    summary: 'Melihat semua barang, jumlah stoknya, dan barang mana yang menipis atau habis.',
    keywords: 'daftar barang filter menipis habis cari',
    audience: 'all',
    openPage: '/stok',
  },
  {
    slug: 'barang-masuk',
    title: 'Barang masuk & koreksi stok',
    group: 'harian',
    summary: 'Menambah stok saat barang datang dari supplier, atau menyamakan stok dengan hasil hitung fisik (stock opname).',
    keywords: 'restock supplier koreksi opname tambah stok',
    audience: 'owner',
    openPage: '/stok',
  },
  {
    slug: 'ubah-barang',
    title: 'Mengubah harga & mengarsipkan barang',
    group: 'harian',
    summary: 'Memperbarui nama, SKU, kategori, satuan, batas menipis, harga, atau foto barang.',
    keywords: 'ubah harga arsip nama foto edit',
    audience: 'owner',
    openPage: '/stok',
  },
  {
    slug: 'riwayat',
    title: 'Riwayat penjualan',
    group: 'harian',
    summary: 'Melihat semua transaksi yang sudah tercatat, lalu membuka detailnya untuk retur atau pembatalan.',
    keywords: 'transaksi penjualan periode filter daftar',
    audience: 'owner',
    openPage: '/penjualan',
  },
  {
    slug: 'retur-batal',
    title: 'Retur dan batal transaksi',
    group: 'harian',
    summary: 'Mengembalikan sebagian barang (retur) atau membatalkan seluruh transaksi yang salah catat.',
    keywords: 'kembali refund salah batal hapus transaksi retur',
    audience: 'owner',
    openPage: '/penjualan',
  },
  {
    slug: 'peringatan',
    title: 'Peringatan stok menipis',
    group: 'harian',
    summary: 'Memberi tahu barang mana yang menipis atau habis, dan membantu menyusun daftar belanja ke supplier.',
    keywords: 'lonceng menipis habis belanja restock',
    audience: 'all',
    openPage: '/peringatan',
  },
  {
    slug: 'dasbor',
    title: 'Dasbor',
    group: 'hasil',
    summary: 'Melihat kinerja toko secara sekilas, dibandingkan dengan periode sebelumnya.',
    keywords: 'omzet laba ringkasan grafik periode',
    audience: 'owner',
    openPage: '/dasbor',
  },
  {
    slug: 'analisis-produk',
    title: 'Analisis produk',
    group: 'hasil',
    summary: 'Mengetahui barang mana yang paling laku, mana yang lambat laku, kapan stok akan habis, dan barang mana yang paling menguntungkan.',
    keywords: 'terlaris lambat laku perkiraan habis untung',
    audience: 'owner',
    openPage: '/dasbor/produk',
  },
  {
    slug: 'laporan',
    title: 'Laporan, cetak & unduh',
    group: 'hasil',
    summary: 'Membuat laporan resmi untuk pembukuan atau untuk diserahkan ke pihak lain, lengkap dengan kop toko.',
    keywords: 'cetak pdf unduh excel csv hpp pajak',
    audience: 'owner',
    openPage: '/laporan',
  },
  {
    slug: 'kategori',
    title: 'Kategori',
    group: 'mengatur',
    summary: 'Mengelompokkan barang, misalnya Sembako atau Minuman, untuk penyaringan di Stok dan untuk laporan per kategori.',
    keywords: 'kelompok ganti nama hapus barang',
    audience: 'owner',
    openPage: '/kategori',
  },
  {
    slug: 'pengaturan',
    title: 'Pengaturan',
    group: 'mengatur',
    summary: 'Aturan penjualan, profil toko, peringatan stok, PIN, dan Mode Kasir dalam satu halaman.',
    keywords: 'setelan jual melebihi stok batas default versi',
    audience: 'owner',
    openPage: '/pengaturan',
  },
  {
    slug: 'mode-kasir',
    title: 'Mode Kasir & PIN',
    group: 'mengatur',
    summary: 'Supaya karyawan bisa memakai Kasir dan melihat stok tanpa bisa melihat harga beli, laba, laporan, atau mengubah pengaturan.',
    keywords: 'pin kasir karyawan lupa kode pemulihan',
    audience: 'all',
    openPage: { owner: '/pengaturan', cashier: '/keluar-mode-kasir' },
  },
  {
    slug: 'istilah',
    title: 'Kamus istilah',
    group: 'istilah',
    summary: 'Arti istilah yang dipakai di aplikasi, seperti SKU, HPP, dan laba kotor.',
    keywords: 'arti hpp laba margin sku omzet',
    audience: 'all',
  },
  {
    slug: 'masalah-umum',
    title: 'Tanya jawab',
    group: 'istilah',
    summary: 'Jawaban untuk pesan dan keadaan yang sering membingungkan, seperti data hilang, layar offline, atau lupa PIN.',
    keywords: 'masalah error offline hilang data bantuan',
    audience: 'all',
  },
] as const satisfies readonly HelpTopicMeta[];

export type HelpTopicSlug = (typeof HELP_TOPICS)[number]['slug'];

export function findHelpTopic(slug: string): (typeof HELP_TOPICS)[number] | undefined {
  return HELP_TOPICS.find((topic) => topic.slug === slug);
}
